apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description with Markdown
  annotations:
    jenkins.io/job-full-name: http://localhost:8080/job/demo-app/job/PR-1
  description: |
    [The Petstore](http://petstore.example.com) is an example API used to show features of the OpenAPI spec.
    - First item
    - Second item
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
